---
title: ""
output: 
  html_document:
    css: !expr here::here("www", "web_report_trust.css")
---

# Frequently Asked Questions

```{r, echo = FALSE}
cur_date <- Sys.Date()
```

<center>**Last Updated:** `r cur_date`</center>
<br><br>

**General**
<br>

<details>
<summary>Who created this dashboard?</summary>
<br>
This dashboard was created by the Urban Institute in partnership with the Chicago Community Trust (CCT) and with the support of the Kresge Foundation.  
<br>
</details> 

<details>
<summary>Why was this dashboard created, and how can it be used?</summary>
<br>
This dashboard was created to track funds flowing through the City of Chicago, Cook County, and State of Illinois for COVID-19 response, and to capture economic recovery programs and infrastructure programs relevant to CCT’s institutional priority areas. The dashboard can be used by community stakeholders, policy researchers, and those interested in learning more about COVID-19 recovery and infrastructure investments to learn about funding allocations and spending priorities across different jurisdictions
<br>

</details>

<details>
<summary>Where does the information in this dashboard come from?</summary>
<br>
Allocation and expenditure data are compiled from federal agency reports, public spending plans, grant announcements, and budget reports from our three geographies of focus. For each program, the data source and source links are listed in the programs table. 
<br>

</details>

<details>
<summary>Why do program names and funding amounts not appear for all projects in the programs chart?</summary>
<br>
The programs chart shows the subset of the total projects included in the dashboard matching the selected policy topic, jurisdiction, and/or legislation. The size of each project box in the chart is proportionate to the share of total funding shown in the chart represented by each project (e.g. if a project represents 10% of the total funding in the chart, the area of that project box will be 10% of the total chart area). For some combinations of policy topic, jurisdiction, and legislation, there are many projects displayed in the chart which forces the size of some projects with smaller funding amounts to be too small to display the project name and allocation.  The name and allocation for those projects is provided in the programs description table. 
<br>

</details>

<details>
<summary>Will the dashboard be updated?</summary>
<br>
Yes. The dashboard will be updated on a continual basis as new information on fund allocations and expenditures becomes publicly available. 
<br>

</details>


<br>
**Recovery Funds Dashboard**
<br>

<details>
<summary>What federal recovery dollars are reflected in this dashboard?</summary>
<br>
This dashboard reflects the subset of funds from the American Rescue Plan Act (ARPA), the Coronavirus Aid, Relief, and Economic Security Act (CARES), and the Coronavirus Response and Relief Supplemental Appropriations Act (CRRSAA) provided directly to Chicago, Cook County, and Illinois that align with the priority policy areas identified by the Chicago Community Trust. In the case of Chicago, the dashboard also reflects a local General Obligation Bond which the city paired with ARPA State and Local Fiscal Recovery Funds (SLFRF) in its Recovery Plan. 
<br>

</details>

<details>
<summary>What federal recovery dollars are not reflected in this dashboard?</summary>
<br>
This dashboard does not include funds that flow directly from the federal government to public housing authorities, school districts or educational institutions, individuals and households, and nongovernmental organizations including nonprofit organizations and private sector businesses. The dashboard also does not include funds used for revenue replacement and operations. Additionally, some funds under SLFRF may fall under categories that do not reflect the CCT’s core priority policy areas of focus and are not captured in the dashboard.  
<br>

</details>

<details>
<summary>How did you select which funding programs to include, and how to categorize them?</summary>
<br>
Selected programs reflect a subset of major federal economic recovery funds and infrastructure funds. For the recovery dashboard, the CCT reviewed funding allocations across jurisdictions and selected programs that align with their institutional priority policy areas in supporting economic recovery: community investment, community safety, household investment, housing, and workforce development. For the infrastructure dashboard, the CCT reviewed funding allocations across jurisdictions and selected programs in the following areas: transit; roads, bridges, and major projects; airports; electric vehicles; water infrastructure; rail; broadband; and traffic safety. We also include total amounts of CARES state and local discretionary funding for which we do not have more specific information on how the funds were spent.  
<br>

</details>

<details>
<summary>What is the difference between ARPA and ARPA State and Local Fiscal Recovery Funds?</summary>
<br>
The State and Local Fiscal Recovery Funds (SLFRF) program is an allocation within ARPA of $350 billion to state, local, and tribal governments across the country. While some ARPA funds can only be used for specific purposes, such as emergency housing or small business assistance, SLFRF are flexible funds that state, county, and local governments can use for a wider range of programs to aid response to and recovery from COVID-19. A full list of applicable uses of SLFRF funds can be found on the [U.S. Department of the Treasury](https://home.treasury.gov/policy-issues/coronavirus/assistance-for-state-local-and-tribal-governments/state-and-local-fiscal-recovery-funds#) website, and more information on each funding source in the dashboard can be found in the glossary. 
<br>

</details>

<details>
<summary>How did you select topics and subtopics to categorize funds?</summary>
<br>
The dashboard categorizes recovery funding allocations across five topics and twenty subtopics that map budget line items from local, county, and state recovery plans to the Chicago Community Trust’s priority policy areas and strategies in its work supporting inclusive recovery. The dashboard categorizes infrastructure funding allocations across eight topics used in data provided by the White House Infrastructure Implementation Task Force. See the glossary for a definition of each topic and subtopic included in the dashboard. The topics may change and may feature additional categories as new information on allocations and expenditures becomes available.  
<br>

</details>

<details>
<summary>Will the dashboard feature expenditure data?</summary>
<br>
The dashboard does not currently feature expenditure data, but will be updated with spending data for selected programs as information becomes available. Spending information can be pulled from public state, county, and local government expenditure reports, including legislative budget reports and mandatory recovery plan performance reports to the U.S. Treasury Department. Spending information for regional entities and tribal governments that received federal funding – which are not included in this dashboard – can be pulled in the same manner. Reporting requirements and deadlines vary by program.
<br>

</details>

<details>
<summary>Why are some funding amounts not exact?</summary>
<br>
The ARPA SLFRF-funded programs included in the dashboard are sourced from line item programs as listed by local, county, and state governments in public ARPA recovery plan reports. In some cases, these reports list multiple programs under one broad spending category, with one budget number for all programs—for instance, a public safety category may include three separate programs listed under one total budget number for all public safety initiatives, without allocations for each program. The “amount exact?” column indicates where we have split the total program budget evenly across multiple line items to generate an estimated average amount per program, and where we have pulled the exact budget number for one line item program.
<br>

</details>

<details>
<summary>How were the programs in the “Explore Spending for Selected Programs” section at the bottom of the dashboard chosen?</summary>
<br>
The dashboard features maps for selected programs for which expenditure data at the zip code level is available. We are working to add more programs to this section as we identify more recovery and infrastructure programs with zip code-level spending data available.  
<br>

</details>


<br>
**Infrastructure Funds Dashboard**
<br>

<details>
<summary>What infrastructure dollars are reflected in this dashboard?</summary>
<br>
This dashboard reflects a subset of funds from the Infrastructure Investment and Jobs Act (IIJA) provided directly to the City of Chicago, Cook County, the Chicago Transit Authority, the Regional Transit Authority (Pace and Metra), Chicago-area airports, and the State of Illinois. Funds come from major programs (at least $1 billion in funding over the five-year spending window) that align with the priority policy areas identified by the CCT and provide funding directly to state and local governments and local transit districts. 
<br>

</details>

<details>
<summary>What infrastructure dollars are not reflected in this dashboard?</summary>
<br>
This dashboard does not track funds spent directly by federal agencies, or funds that flow directly from the federal government to utility providers or public utility districts, economic development authorities, school districts, nonprofit organizations, and private sector businesses. 

Funding allocated to entities such as Amtrak, economic development authorities, and regional planning councils for spending in the relevant geographies may be added to the dashboard as data become available.  The dashboard does not currently display “pass-through funding,” that is, funding passed from its original recipient to another jurisdiction where it is ultimately spent.
<br>

</details>

<details>
<summary>What is the difference between allocations and awards?</summary>
<br>
Allocated funds are designated total possible funds for a jurisdiction for a specific project purpose. Awarded funds are the final amount disbursed to a jurisdiction, and may reflect subdivisions of an allocation.  
<br>

</details>
